## 14. Lambda Functions 

A lambda funciton is small anonymous(Unnamed) functions.

syntax:

Normal function
    lambda(func, sequence)

anonymous function:
    (lambda,sequence)


Lambda:
    map()
    filter()
    reduce()
    apply()

lambda argument:expression

No def keyword

single expression

return value automatically

In [1]:
# find the square of number 10

# Normal

def squareNum(x):
    return x*x
squareNum(10)

100

In [5]:
(lambda x:x**2)(10)

100

In [7]:
# write a program to check user can vote or not

age = int(input("Enter your age: "))

if age>=18:
    print("Vote Now")
else:
    print("Not Elegible")

Enter your age:  17

Not Elegible

In [10]:
(lambda a1:print("Vote Now")  if a1>=18 else print("Not Elegible"))(age)

Not Elegible

Normal Function : Lambda

Anonymous :
        filter()
        map()
        reduce()
        apply()

In [12]:

def addTwo(a,b):
    return a+b
addTwo(10,12)

22

In [13]:
(lambda a,b:a+b)(10,12)

22

## lambda with filter

In [16]:
list1 = [1,2,3,4,5,6,7,8,9]

def evenNum(x):
    if x%2==0:
        return "Even"

evenNum(10)

'Even'

In [17]:
# syntax:
# filter(func,sequence)

In [20]:
list1 = [1,2,3,4,5,6,7,8,9]

tuple(filter(evenNum,list1))

(2, 4, 6, 8)

In [28]:
list(filter(lambda a:a%2==0, list1))

[2, 4, 6, 8]

In [30]:
fruits = ["apple","banana","mango"]

for i in fruits:
    if len(i)>5:
        print(i)

banana

In [32]:
def morethanFive(x):
    if len(x)>5:
        return x
morethanFive("apple")

In [34]:
fruits = ["apple","banana","mango"]


list(filter(morethanFive,fruits))

['banana']

In [36]:
list(filter(lambda a:len(a)>5,fruits))

['banana']

# lambda with map()


syntax:
map(func,sequence)

In [40]:
list1 = [1,2,3,4,5,6,7,8,9]


def sqrNum(x):
    return x*x
sqrNum(10)

100

In [42]:
list(map(sqrNum,list1))

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [44]:
list(map(lambda a:a*a, list1))

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [46]:
x = [1,2,3,4,5,6,7,8,9]
# [1,2] = [3,3] = [6,4]=[10,5]= [15,6]=[21,7]=[28,8]=[36,9]= [45,10] = 55

In [48]:
from functools import reduce

In [49]:
help(reduce)

Help on built-in function reduce in module _functools:

reduce(function, iterable, /, initial=<unrepresentable>)
    Apply a function of two arguments cumulatively to the items of an iterable, from left to right.

    This effectively reduces the iterable to a single value.  If initial is present,
    it is placed before the items of the iterable in the calculation, and serves as
    a default when the iterable is empty.

    For example, reduce(lambda x, y: x+y, [1, 2, 3, 4, 5])
    calculates ((((1 + 2) + 3) + 4) + 5).

In [50]:
# reduce(lambda x, y: x+y, [1, 2, 3, 4, 5])

In [53]:
x = [1,2,3,4,5,6,7,8,9,10]


def reduceValue(x,y):
    return x+y
reduceValue(10,12)

22

In [54]:
reduce(reduceValue,x)

55

In [55]:
reduce(lambda a,b:a+b,x)

55

In [56]:
import pandas as pd

In [57]:
series = [1,2,3,4,5,6,7]
print(series)

[1, 2, 3, 4, 5, 6, 7]

In [59]:
df = pd.DataFrame(series)
df

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7

In [60]:
list1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

print(list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [61]:
df1 = pd.DataFrame(list1)
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [65]:
# for i in range(df1):
#     print(i)

In [69]:
for i in list1:
    # print(i)
    for j in i:
        print(j**2)

1
4
9
16
25
36
49
64
81

In [70]:
# apply()

# var.apply(func)

In [71]:
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [72]:
df2 =df1.apply(lambda a:a*a)
df2

    0   1   2
0   1   4   9
1  16  25  36
2  49  64  81